-- Add portfolio-specific fields to the projects table
ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS demo_url TEXT,
ADD COLUMN IF NOT EXISTS screenshots TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS video_url TEXT,
ADD COLUMN IF NOT EXISTS technologies TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS challenge TEXT,
ADD COLUMN IF NOT EXISTS solution TEXT,
ADD COLUMN IF NOT EXISTS results TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS metrics JSONB,
ADD COLUMN IF NOT EXISTS client_name TEXT,
ADD COLUMN IF NOT EXISTS client_industry TEXT,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;

-- Create policy for public portfolio viewing
CREATE POLICY "Anyone can view public projects"
ON public.projects FOR SELECT
USING (is_public = true AND status = 'completed');

-- Insert sample portfolio data
INSERT INTO public.projects (
  title, description, service_category, status, 
  demo_url, screenshots, video_url, technologies,
  is_featured, is_public, challenge, solution, results,
  metrics, client_name, client_industry, completed_at
) VALUES 
(
  'E-Commerce Platform Luxe',
  'Plateforme e-commerce complète avec paiement intégré, gestion des stocks et analytics en temps réel.',
  'programming',
  'completed',
  'https://demo-ecommerce.brandhub.ma',
  ARRAY['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
  NULL,
  ARRAY['React', 'Node.js', 'PostgreSQL', 'Stripe', 'Tailwind CSS'],
  true,
  true,
  'Le client avait besoin d''une solution e-commerce performante capable de gérer plus de 10 000 produits avec un temps de chargement minimal.',
  'Nous avons développé une architecture microservices avec cache Redis, optimisation des images et CDN global pour garantir des performances optimales.',
  ARRAY['+250% de conversions', 'Temps de chargement < 2s', '99.9% uptime'],
  '{"conversions": 250, "loadTime": "1.8s", "uptime": 99.9, "products": 12000}',
  'Maison Luxe',
  'Mode & Luxe',
  NOW() - INTERVAL '30 days'
),
(
  'Application Mobile Fitness',
  'Application mobile cross-platform pour le suivi fitness avec coaching IA et synchronisation wearables.',
  'programming',
  'completed',
  'https://demo-fitness.brandhub.ma',
  ARRAY['https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=800', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800'],
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  ARRAY['React Native', 'Firebase', 'TensorFlow', 'Apple HealthKit', 'Google Fit'],
  true,
  true,
  'Créer une expérience utilisateur fluide intégrant l''IA pour des recommandations personnalisées tout en respectant la vie privée.',
  'Développement d''un modèle ML on-device pour les recommandations, garantissant la confidentialité des données utilisateur.',
  ARRAY['500K+ téléchargements', '4.8★ App Store', 'Rétention 45%'],
  '{"downloads": 500000, "rating": 4.8, "retention": 45, "dailyActiveUsers": 75000}',
  'FitLife Pro',
  'Santé & Bien-être',
  NOW() - INTERVAL '45 days'
),
(
  'Identité Visuelle Restaurant Gastronomique',
  'Création complète de l''identité visuelle incluant logo, charte graphique, packaging et supports marketing.',
  'graphics',
  'completed',
  NULL,
  ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
  NULL,
  ARRAY['Adobe Illustrator', 'Photoshop', 'InDesign', 'After Effects'],
  true,
  true,
  'Créer une identité visuelle haut de gamme reflétant l''excellence culinaire et l''héritage marocain du restaurant.',
  'Design inspiré de la géométrie traditionnelle marocaine avec une touche contemporaine, utilisant des couleurs riches et des textures subtiles.',
  ARRAY['Prix du meilleur design 2024', '+180% reconnaissance marque', 'Couverture médiatique nationale'],
  '{"brandRecognition": 180, "mediaFeatures": 15, "customerSatisfaction": 98}',
  'Le Jardin Secret',
  'Gastronomie',
  NOW() - INTERVAL '60 days'
),
(
  'Campagne Marketing Digital',
  'Stratégie marketing 360° incluant SEO, publicité payante, content marketing et influence.',
  'business',
  'completed',
  NULL,
  ARRAY['https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=800', 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800'],
  NULL,
  ARRAY['Google Ads', 'Meta Ads', 'SEMrush', 'HubSpot', 'Analytics'],
  false,
  true,
  'Lancer une nouvelle marque sur un marché saturé avec un budget marketing limité.',
  'Approche data-driven avec focus sur le marketing de contenu et les micro-influenceurs pour maximiser le ROI.',
  ARRAY['ROI 450%', '1M+ impressions', '25K nouveaux clients'],
  '{"roi": 450, "impressions": 1200000, "newCustomers": 25000, "cpc": 0.35}',
  'TechStart Innovation',
  'Technologie',
  NOW() - INTERVAL '20 days'
),
(
  'Site Web Corporate',
  'Site vitrine moderne avec animations, multilingue et optimisé pour les performances.',
  'programming',
  'completed',
  'https://demo-corporate.brandhub.ma',
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800'],
  NULL,
  ARRAY['Next.js', 'TypeScript', 'Framer Motion', 'Sanity CMS', 'Vercel'],
  true,
  true,
  'Moderniser la présence digitale d''un groupe industriel tout en maintenant une image professionnelle et accessible.',
  'Architecture headless CMS permettant aux équipes internes de gérer le contenu facilement, avec animations subtiles pour dynamiser l''expérience.',
  ARRAY['Score Lighthouse 98', '+300% trafic organique', 'Temps moyen 4min'],
  '{"lighthouseScore": 98, "organicTraffic": 300, "avgSessionDuration": "4:12", "bounceRate": 25}',
  'Groupe Atlas Industries',
  'Industrie',
  NOW() - INTERVAL '15 days'
),
(
  'Production Vidéo Publicitaire',
  'Spot publicitaire TV 30s avec production complète, de la conception au montage final.',
  'content',
  'completed',
  NULL,
  ARRAY['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800', 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800'],
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  ARRAY['Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Cinema 4D'],
  false,
  true,
  'Créer un spot mémorable en 30 secondes capable de transmettre les valeurs de la marque et générer de l''émotion.',
  'Storytelling centré sur l''humain avec une direction artistique cinématographique et une bande sonore originale.',
  ARRAY['15M vues', 'Viral sur réseaux sociaux', 'Prix Créativité 2024'],
  '{"views": 15000000, "shares": 250000, "engagement": 8.5}',
  'Maroc Telecom',
  'Télécommunications',
  NOW() - INTERVAL '40 days'
);